// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(FestivalDbContext))]
    partial class FestivalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "The Weekenders"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Northern Lights"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Stockholm Beats"
                        });
                });

            modelBuilder.Entity("ArtistPerformance", b =>
                {
                    b.Property<int>("ArtistsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerformancesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArtistsId", "PerformancesId");

                    b.HasIndex("PerformancesId");

                    b.ToTable("ArtistPerformance");

                    b.HasData(
                        new
                        {
                            ArtistsId = 1,
                            PerformancesId = 1
                        },
                        new
                        {
                            ArtistsId = 2,
                            PerformancesId = 2
                        },
                        new
                        {
                            ArtistsId = 3,
                            PerformancesId = 3
                        });
                });

            modelBuilder.Entity("Attendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Attendees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Anna Andersson"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Erik Johansson"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sara Karlsson"
                        });
                });

            modelBuilder.Entity("Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LengthMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PerformanceTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("Performances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Pop",
                            LengthMinutes = 60,
                            PerformanceTime = new DateTime(2026, 8, 22, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StageId = 1
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Rock",
                            LengthMinutes = 75,
                            PerformanceTime = new DateTime(2026, 8, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StageId = 2
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Electronic",
                            LengthMinutes = 90,
                            PerformanceTime = new DateTime(2026, 8, 22, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StageId = 3
                        });
                });

            modelBuilder.Entity("Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Main Stage"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rock Stage"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Electronic Stage"
                        });
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttendeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceSek")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidThrough")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttendeeId")
                        .IsUnique();

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendeeId = 1,
                            PriceSek = 750,
                            PurchaseDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidThrough = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AttendeeId = 2,
                            PriceSek = 750,
                            PurchaseDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidThrough = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AttendeeId = 3,
                            PriceSek = 1000,
                            PurchaseDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidThrough = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ArtistPerformance", b =>
                {
                    b.HasOne("Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Performance", null)
                        .WithMany()
                        .HasForeignKey("PerformancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Performance", b =>
                {
                    b.HasOne("Stage", "StageNavigation")
                        .WithMany("Performances")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StageNavigation");
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.HasOne("Attendee", "AttendeeNavigation")
                        .WithOne("TicketNavigation")
                        .HasForeignKey("Ticket", "AttendeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendeeNavigation");
                });

            modelBuilder.Entity("Attendee", b =>
                {
                    b.Navigation("TicketNavigation");
                });

            modelBuilder.Entity("Stage", b =>
                {
                    b.Navigation("Performances");
                });
#pragma warning restore 612, 618
        }
    }
}
